musica/imusica/urls.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView
from django.conf.urls import include, url, patterns
from django.contrib import admin
from views import *
from models import *
from rest_framework.urlpatterns import format_suffix_patterns



admin.autodiscover()

urlpatterns = patterns('',

url(r'^$',Inici.as_view(),),
url(r'^api/$', IniciApiRest.as_view(),),

#List models
# ex html: /app/Artist
# ex xml: /app/Artist.xml
# ex json: /app/Artist.json
url(r'^Artist.json/$',artistjson, name='artist_list'),
url(r'^Artist.xml/$',artistxml, name='artist_list'),
url(r'^Artist/$',Artists.as_view(), name='artist_list'),
url(r'^Album.json/$',albumjson, name='album_list'),
url(r'^Album.xml/$',albumxml, name='album_list'),
url(r'^Album/$',Albums.as_view(), name='album_list'),
url(r'^Song.json/$',songjson, name='song_list'),
url(r'^Song.xml/$',songxml, name='song_list'),
url(r'^Song/$',Songs.as_view(), name='song_list'),
url(r'^Companyia.json/$',companyiajson, name='companyia_list'),
url(r'^Companyia.xml/$',companyiaxml, name='companyia_list'),
url(r'^Companyia/$',Companyies.as_view(), name='companyia_list'),

#	DETALLS de cada artista

    # Artist details, ex: /app/Artist/1.json
    url(r'^Artist/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        ArtistDetail.as_view(),
        name='artist_detail'),

    # Create an artist, ex /app/Artist/create
    url(r'^Artist/create/$',
        ArtistCreate.as_view(),
        name='artist_create'),

    # Edit artist details, ex /app/Artist/1/edit
    url(r'^Artist/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Artist,
            form_class=ArtistForm),
        name='artist_edit'),

#	DETALLS de cada canso

	# SONGS details, ex.: /app/Song/1.json
    url(r'^Song/(?P<pk>\d+)(\.(?P<extension>(json|xml)))$',
        SongDetail.as_view(),
        name='song_detail'),

    # Create a song, ex: /app/Song/create/
    url(r'^Song/create/$',
        SongCreate.as_view(),
        name='song_create'),

    # Edit an artist song details, ex: /app/Artist/1/Song/1/edit/
    url(r'^Artist/(?P<pkr>\d+)/Song/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Song,
            form_class=SongForm),
        name='song_edit'),
    # Create an artist review using function, ex: /app/Artist/1/reviews/create/
    url(r'^Artist/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),
        
        
## Songs of Artist

	# Artist songs list, ex.: /app/Artist/1/Song.json
    url(r'^Artist/(?P<pk>\d+)/Song\.(?P<extension>(json|xml))$',
        SongList.as_view(),
        name='song_list'),

    # Artist song details, ex.: /app/Artist/1/Song/1.json
    url(r'^Artist/(?P<pkr>\d+)/Song/(?P<pk>\d+)(\.(?P<extension>(json|xml)))?$',
        SongDetail.as_view(),
        name='song_detail'),

    # Create a artist song, ex: /app/Artist/1/Song/create/
    url(r'^Artist/(?P<pk>\d+)/Song/create/$',
        SongCreate.as_view(),
        name='song_create'),

    # Edit an artist song details, ex: /app/Artist/1/Song/1/edit/
    url(r'^Artist/(?P<pkr>\d+)/Song/(?P<pk>\d+)/edit/$',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Song,
            form_class=SongForm),
        name='song_edit'),
    # Create an artist review using function, ex: /app/Artist/1/reviews/create/
    url(r'^Artist/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),


)

### RESTful urls

urlpatterns += [
    url(r'^api/auth/',
        include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/Companyia/$',
        APICompanyiaList.as_view(), name='companyia-list'),
    url(r'^api/Companyia/(?P<pk>\d+)/$',
        APICompanyiaDetail.as_view(), name='companyia-detail'),
    url(r'^api/Artist/$',
        APIArtistList.as_view(), name='artist-list'),
    url(r'^api/Artist/(?P<pk>\d+)/$',
        APIArtistDetail.as_view(), name='artist-detail'),
    url(r'^api/Album/$',
        APIAlbumList.as_view(), name='album-list'),
    url(r'^api/Album/(?P<pk>\d+)/$',
        APIAlbumDetail.as_view(), name='album-detail'),
    url(r'^api/Song/$',
        APISongList.as_view(), name='song-list'),
    url(r'^api/Song/(?P<pk>\d+)/$',
        APISongDetail.as_view(), name='song-detail'),
    url(r'^api/Artistreviews/$',
        APIArtistReviewList.as_view(), name='artistreview-list'),
    url(r'^api/Artistreviews/(?P<pk>\d+)/$',
        APIArtistReviewDetail.as_view(), name='artistreview-detail'),

]

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api','json', 'xml'])

musica/musica/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from imusica.views import *
from imusica.models import *
from django.contrib.auth.views import login, logout
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^$',mainpage),

    url(r'^admin/',include(admin.site.urls)),
    url(r'^app/', include('imusica.urls', namespace='imusica')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name = 'logout'),

    #url(r'^accounts/profile/$', login, name='login'),
    url(r'^accounts/profile/$', include('imusica.urls', namespace='imusica')),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })
    ]

musica/imusica/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date

class Companyia(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    website = models.URLField(blank=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

class Artist(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50, blank=True, default='City')
    country = models.CharField(max_length=50, blank=True, default='Country')
    website = models.URLField(blank=True)
    idNumber = models.IntegerField(blank=True, null=True)
    companyia = models.ForeignKey(Companyia, null = True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('imusica:artist_detail', kwargs={'pk': self.pk})
#    def averageRating(self):
#        ratingSum = sum([float(review.rating) for review in self.artistreview_set.all()])
#        reviewCount = self.artistreview_set.count()
#        return ratingSum / reviewCount

class Album(models.Model):
    name = models.CharField(max_length=50)
    idNumber = models.TextField(null=True)
    artista = models.ForeignKey(Artist, null=True)
    companyia = models.ForeignKey(Companyia, null = True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

class Song(models.Model):
    name = models.CharField(max_length=50)
    style = models.CharField(max_length=50, blank=True, default='Pop')
    texte = models.CharField(max_length=50, blank=True, default='Lletra completa')
#    artista = models.ForeignKey(Artist, null=True)
    artista = models.ForeignKey(Artist, null=True, related_name='songs')
    album = models.ForeignKey(Album, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('imusica:song_detail', kwargs={'pkr': self.artist.pk, 'pk': self.pk})

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

class ArtistReview(Review):
    artist = models.ForeignKey(Artist)

musica/imusica/forms.py
from django.forms import ModelForm
from models import Artist, Song

class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        exclude = ('user', 'date',)

class SongForm(ModelForm):
    class Meta:
        model = Song
        exclude = ('user', 'date', 'artista')

musica/imusica/templates/albums.html
{% for album in object_list %}
<p>
<b>Nom: </b> {{album.name}}<br>
<b>Identificador: </b> {{album.idNumber}}<br>
<b>Artista: </b> {{album.artista.name}}<br>
<b>Companyia: </b> {{album.companyia.name}}<br>

********************</p>
{% endfor %}

musica/imusica/templates/artist_detail.html
{% extends "base.html" %}
{% block title %} iMusica - {{ artist.name}}{% endblock %}

{% block content %}
<span vocab="http://schema.org/" typeof="Musica">
<h1>
    <span property="name"> {{ artist.name }} </span>
    {% if user == artist.user %}
      (<a href="{% url 'imusica:artist_edit' artist.id %}">edit</a>)
    {% endif %}
</h1>
<h2>Address:</h2>
<p>
  <span property="address"> {{ artist.city }}, {{ artist.country }} </span>
     <br/>
</p>
<h2>
    Songs
    {% if user.is_authenticated %}
    (<a href="{% url 'imusica:song_create' artist.id %}">add</a>)
    {% endif %}
</h2>
<ul>
    {% for song in artist.song.all %}
        <li><a href="{% url 'imusica:song_detail' artist.name song.name  %}">
            {{ song.name }}</a></li>
    {% empty %}<li>Sorry, no songs for this artist yet.</li>
    {% endfor %}
</ul>
<ul>
	{% for song in object_list %}
	<p>
	<a href= "{{song.id}}" > Enllaç a la cançó </a> <br>
	<b>Nom: </b> {{song.name}}<br>
	<b>Estil: </b> {{song.style}}<br>
	<b>Text: </b> {{song.texte}}<br>
	<b>Artista: </b> {{song.artista.name}}<br>
	<b>Album: </b> {{song.album.name}}<br>
	********************</p>
	{% empty %}<li>Ho sentim, no hi ha cançons per aquest artista.</li>
	{% endfor %}
</ul>
<h2>Reviews</h2>
{% if artist.artistreview_set.all|length > 0 %}
<span rel="aggregateRating">
    <p typeof="AggregateRating">
        Average rating <span property="ratingValue">{{ artist.averageRating|stringformat:".1f" }}</span>
        {% with artist.artistreview_set.all|length as reviewCount %}
        from <span property="reviewCount">{{ reviewCount }}</span> review{{ reviewCount|pluralize }}
        {% endwith %}
    </p>
</span>
<ul rel="review">
    {% for review in artist.artistreview_set.all %}
        <li typeof="Review">
            <p rel="reviewRating" typeof="Rating">
                <span property="worstRating" content="{{ RATING_CHOICES.0.0 }}"></span>
                <span property="ratingValue">{{ review.rating }}</span> star{{ review.rating|pluralize }}
                {% with RATING_CHOICES|last as best %}
                <span property="bestRating" content="{{ best.0 }}"></span>
                {% endwith %}
            </p>
            <p property="description">{{ review.comment }}</p>
            <p>Created by <span property="author">{{ review.user }}</span> on
                <span property="datePublished" content="{{ review.date|date:'Y-m-d' }}">{{ review.date }}</span></p>
        </li>
    {% endfor %}
</ul>
</span>
{% endif %}

<h3>Add Review</h3>
<form action="{% url 'imusica:review_create' artist.id %}" method="post">
    {% csrf_token %}
    Message: <textarea name="comment" id="comment" rows="4"></textarea>
    <p>Rating:</p>
    <p>{% for rate in RATING_CHOICES %}
    <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.1 }}" />
    <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
    <br/>{% endfor %}
    </p>
    <input type="submit" value="Review" />
</form>


{% endblock %}
{% block footer %}
    Created by <span property="author"> {{ artist.user }} </span> on
    <span property="date" content="{{ artist.date|date:'Y-m-d' }}"> {{ artist.date }} </span>
{% endblock %}

musica/imusica/templates/artists.html
{% for artista in object_list %}
<p>
<a href= "{{artista.id}}" > Enllaç a l'artista </a> <br>
<b>Nom: </b> {{artista.name}}<br>
<b>Ciutat: </b> {{artista.city}}<br>
<b>Pais: </b> {{artista.country}}<br>
<b>Pagina web: </b> {{artista.website}}<br>
<b>Identificador: </b> {{artista.idNumber}}<br>
<b>Companyia: </b> {{artista.companyia.name}}<br>
********************</p>
{% endfor %}

musica/imusica/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet"
  href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-2.2.3.js"></script>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>

<div id="header">
    {% block header %}
        {% if user.username %}
            <p>User: {{ user.username }} | <a href="{% url 'logout' %}?next={{request.path}}">logout</a></p>
        {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">login</a></p>
        {% endif %}
    {% endblock %}
</div>

<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/app/">Home</a></li>
        </ul>
    {% endblock %}
</div>

<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

<div id="footer">
    {% block footer %}{% endblock %}
</div>

</body>
</html>

musica/imusica/templates/companyies.html
  {% for companyia in object_list %}
  <p>
  <b>Nom: </b> {{companyia.name}}<br>
  <b>Ciutat: </b> {{companyia.city}}<br>
  <b>Pagina web: </b> {{companyia.website}}<br>
  ********************</p>
  {% endfor %}

musica/imusica/templates/form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}<script>
  $(function(){
    $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });
    $("#id_city").autocomplete({
      source: function(request,	response){
        $.ajax({
          url: "http://ws.geonames.org/searchJSON",
          dataType:	"jsonp",
          data:	{
            featureClass:	"P",
            maxRows: 10,
            name_startsWith: request.term,
            username:	"xavi_bmx"
          },
          success: function(data)	{
            response($.map(data.geonames, function(item)	{
              return	{
                label: item.name + (item.adminName1	?	", " +
                    item.adminName1	:	"")	+	", " + item.countryName,
                value: item.name,
                city: item.adminName1,
                countryName: item.countryName
              }
            }));
          }
        });
      },
      minLength: 2,
      select:	function(event,ui) {
        if	(ui.item)	{
          $("#id_city").val(ui.item.city);
          $("#id_country").val(ui.item.countryName);
        }
      }
    });
  });
</script>
<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

musica/imusica/templates/index.html
<h1> MAIN MUSIC </h1>
<p> <== <a href= "/" > Tornar a la pagina principal</a></p>
<p> ==> <a href= "/app/api" > Anar a l'API</a></p>
<ul>
	<li><p>Artists</p>
		<a href= "Artist" > HTML</a> <br>
		<a href="Artist.xml"> XML </a><br>
		<a href="Artist.json"> JSON </a><br> </li>
	<li><p>Album</p>
		<a href= "Album" > HTML</a> <br>
		<a href="Album.xml"> XML </a><br>
		<a href="Album.json"> JSON </a><br></li>
	<li><p>Song</p>
		<a href= "Song" > HTML</a></li>
		<a href="Song.xml"> XML </a><br>
		<a href="Song.json"> JSON </a><br></li>
	<li><p>Companyia</p>
		<a href= "Companyia" > HTML</a></li>
		<a href="Companyia.xml"> XML </a><br>
		<a href="Companyia.json"> JSON </a><br></li>
</ul>

musica/imusica/templates/index2.html
<h1> API RESTful </h1>
<p> <== <a href= "/app" > Tornar a l'app</a></p>

<ul>
	<li><p>Artists</p>
		<a href= "Artist" > API per Artist</a> </li>
	<li><p>Album</p>
		<a href= "Album" > API per Album</a></li>
	<li><p>Song</p>
		<a href= "Song" > API per Song</a></li>
	<li><p>Companyia</p>
		<a href= "Companyia" > API per Companyia</a></li>

</ul>

musica/imusica/templates/song_detail.html
{% extends "base.html" %}
{% block title %}MyMusic ­‐ {{ song.name }}{%	endblock %}

{% block content %}
<span vocab="http://schema.org/" typeof="Musica">	
<h1>	
	<span property="name">{{ song.name }}</span>
	{% if user == song.user %}
		(<a	href="{% url 'imusica:song_edit' song.artista.id song.id %}">edit</a>)	
 	{% endif %}
</h1>	

<p><span property="info">{{ song.artista}}, {{ song.album}}</br></br>
{{ song.style }}</br></br>
{{ song.texte }}</p></span>

<h3>Add Review</h3>
<form action="{% url 'imusica:review_create' song.id %}" method="post">
    {% csrf_token %}
    Message: <textarea name="comment" id="comment" rows="4"></textarea>
    <p>Rating:</p>
    <p>{% for rate in RATING_CHOICES %}
    <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.1 }}" />
    <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label>
    <br/>{% endfor %}
    </p>
    <input type="submit" value="Review" />
</form>


{% endblock %}

{% block footer %}
    Created by <span property="author"> {{ song.user }} </span> on
    <span property="date" content="{{ song.date|date:'Y-m-d' }}"> {{ song.date }} </span>
{% endblock %}

musica/imusica/templates/songs.html
{% for song in object_list %}
<p>
<b>Nom: </b> {{song.name}}<br>
<b>Estil: </b> {{song.style}}<br>
<b>Text: </b> {{song.texte}}<br>
<b>Artista: </b> {{song.artista.name}}<br>
<b>Album: </b> {{song.album.name}}<br>
********************</p>
{% endfor %}